export const CURRENT_CATEGORY = 'CURRENT_CATEGORY';

export const ITEM_CATEGORIE = 'ITEM_CATEGORIE';
export const ADD_ITEM = 'ADD_ITEM';
export const VALIDATE_ITEM = 'VALIDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const FOCUS_ITEM = 'FOCUS_ITEM';
export const DONE_ITEM = 'DONE_ITEM';
export const UPDATE_ITEMSTAG = ' UPDATE_ITEMSTAG';
export const UPDATE_ITEMSDELETEDTAG = 'UPDATE_ITEMSDELETEDTAG';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const ITEM_STATE = 'ITEM_STATE';
export const CURRENT_ITEM = 'CURRENT_ITEM';
export const ITEM_BELONGSPROJECT = 'ITEM_BELONGSPROJECT';

export const ADD_TAG = 'ADD_TAG';
export const VALIDATE_TAG = 'VALIDATE_TAG';
export const DELETE_TAG = 'DELETE_TAG';
export const UPDATE_TAG = 'UPDATE_TAG';
